const SET_NEW_TASK = "@loginTypes/SET_NEW_TASK ";
const ADD_NEW_TASK_ERROR = "@loginTypes/ADD_NEW_TASK_ERROR";
const GET_NEW_TASK = "@loginTypes/GET_NEW_TASK";
const SET_TASKS_OF_PROJECT = "@loginTypes/SET_TASKS_OF_PROJECT";
const TASKS_OF_PROJECT_ERROR = "@loginTypes/TASKS_OF_PROJECT_ERROR";
const GER_TASKS_OF_PROJECT = "@loginTypes/GER_TASKS_OF_PROJECT";

export default {
  SET_NEW_TASK,
  ADD_NEW_TASK_ERROR,
  GET_NEW_TASK,
  SET_TASKS_OF_PROJECT,
  TASKS_OF_PROJECT_ERROR,
  GER_TASKS_OF_PROJECT,
};