const SET_NEW_PROJECT = "@loginTypes/SET_NEW_PROJECT ";
const ADD_NEW_PROJECT_ERROR = "@loginTypes/ADD_NEW_PROJECT_ERROR";
const GET_NEW_PROJECT = "@loginTypes/GET_NEW_PROJECT";

export default {
  SET_NEW_PROJECT ,
  ADD_NEW_PROJECT_ERROR,
  GET_NEW_PROJECT,
};
