const SET_LOGIN_STATUS_TRUE = "@loginTypes/SET_LOGIN_STATUS_TRUE";
const LOGIN_STATUS_ERROR = "@loginTypes/LOGIN_STATUS_ERROR";
const GET_LOGIN_STATUS_TRUE = "@loginTypes/GET_LOGIN_STATUS_TRUE";

export default {
  SET_LOGIN_STATUS_TRUE,
  LOGIN_STATUS_ERROR,
  GET_LOGIN_STATUS_TRUE,
};
