const ADD_NEW_PROJECT = "@projectsTypes./ADD_NEW_PROJECT";
const GET_PROJECTS = "@projectsTypes/GET_PROJECTS";
const ADD_NEW_PROJECT_FAILUER = "@projectsTypes/ADD_NEW_PROJECT_FAILUER";
const DELET_PROJECT = "@projectsTypes/DELET_PROJECT";
const DELET_PROJECT_ERROR = "@projectsTypes/DELET_PROJECT_ERROR";

export default {
  ADD_NEW_PROJECT,
  GET_PROJECTS,
  ADD_NEW_PROJECT_FAILUER,
  DELET_PROJECT,
  DELET_PROJECT_ERROR
};
