const ADD_NEW_TASK = "tasksTypes/ADD_NEW_TASK";
const AAD_TASK_COMMENT = "tasksTypes/AAD_TASK_COMMENT";
const ADD_NEW_TASK_FAILUER = "tasksTypes/ADD_NEW_TASK-FAILUER";
const GET_TASKS_BY_PROJECT = "@tasksTypes/GET_TASKS_BY_PROJECT";
const GET_COMMENTS_BY_TASK = "@tasksTypes/GET_COMMENTS_BY_TASK";
const DELET_TASK = "@tasksTypes/DELET_TASK";
const DELET_TASK_ERROR = "@tasksTypes/DELET_TASK_ERROR";

export default {
  ADD_NEW_TASK,
  AAD_TASK_COMMENT,
  ADD_NEW_TASK_FAILUER,
  GET_TASKS_BY_PROJECT,
  GET_COMMENTS_BY_TASK,
  DELET_TASK,
  DELET_TASK_ERROR
};
