const LOGIN = "@loginTypes/LOGIN";
const LOGIN_FAILURE = "@loginTypes/LOGIN_FAILURE";
const GET_LOGIN_STATUS = "@loginTypes/GET-LOGIN-STATUS";
const DELET_LOGIN_ERROR = "@loginTypes/DELET_LOGIN_ERROR";
const RECIVE_LOGIN_STATUS = "@loginTypes/RECIVE_LOGIN_STATUS";
const ASK_FOR_LOGEDMEMBER = "@loginTypes/ASK_FOR_LOGEDMEMBER";
const GET_LOGEDMEMBER = "@loginTypes/GET_LOGEDMEMBER";
const SET_LOGOUT = "@loginTypes/SET_LOGOUT";

export default {
  LOGIN,
  LOGIN_FAILURE,
  ASK_FOR_LOGEDMEMBER,
  GET_LOGEDMEMBER,
  SET_LOGOUT,
  GET_LOGIN_STATUS,
  DELET_LOGIN_ERROR,
  RECIVE_LOGIN_STATUS
};
