const ASK_FOR_MEMBERS = "@lmembersType.js/ASK_FOR_MEMBERS";
const GET_MEMBERS = "@lmembersType.js/GET_MEMBERS";
const ADD_NEW_MEMBER = "@lmembersType.js/ADD_NEW_MEMBER";
const ADD_NEW_MEMBER_FAILUER = "@lmembersType.js/ADD_NEW_MEMBER_FAILUER";
const SET_MEMBER_FAILUER_DELET = "@lmembersType.js/SET_MEMBER_FAILUER_DELET";
const GET_MEMBER_FAILUER_DELET = "@lmembersType.js/GET_MEMBER_FAILUER_DELET";

export default {
  ASK_FOR_MEMBERS,
  GET_MEMBERS,
  ADD_NEW_MEMBER,
  ADD_NEW_MEMBER_FAILUER,
  SET_MEMBER_FAILUER_DELET,
  GET_MEMBER_FAILUER_DELET
};
